import 'dotenv/config';

const {
  BOILER_PROD_DATABASE_USER,
  BOILER_PROD_DATABASE_PASSWORD,
  BOILER_PROD_DATABASE_HOST,
  BOILER_PROD_DATABASE_NAME,
  BOILER_PROD_DATABASE_PORT,
  BOILER_PROD_DATABASE_MAX_CONNECTIONS,
  BOILER_PROD_PAPERTRAIL_PORT,
  BOILER_PROD_PAPERTRAIL_HOST,
} = process.env;

export default {
  NODE_ENV: 'production',
  DATABASE_USER: BOILER_PROD_DATABASE_USER,
  DATABASE_PASSWORD: BOILER_PROD_DATABASE_PASSWORD,
  DATABASE_HOST: BOILER_PROD_DATABASE_HOST,
  DATABASE_NAME: BOILER_PROD_DATABASE_NAME,
  DATABASE_PORT: BOILER_PROD_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: BOILER_PROD_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: BOILER_PROD_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: BOILER_PROD_PAPERTRAIL_HOST,
};
